### ISSUE TITLE
works only up to the android Marshmallow

### ISSUE THREAD

**Issue by RaulCorreia** [rmrs/react-native-settings#22] opened 2018-10-17 11:53 UTC
I really enjoyed using this library, I was testing on an android with api 23 and it worked very well, but when testing on an android from api 24 it did not work anymore.
would that be it? or is there anything I can do to make it work on android 24+

**Comment by erezrokah** [comment] 2018-10-17 13:54
Hey @RaulCorreia thank you for using the library and glad to hear you're enjoying it :)

Can you please provide more specific details?
1. What doesn't work:

* Getting a setting
* Opening the settings application in a specific setting
* listening to events

2. Do you have any logs (builds logs Android logcat logs you can provide)?

3. Can you setup an example repo that reproduces this issue?

Thanks :)

**Comment by RaulCorreia** [comment] 2018-10-17 17:43
I was using getSetting to start the state and expose the user that the gps was already on, and I used the listening to update the real time if I disconnect the gps, but only worked all these functions until the android 6, from the 7 none action works, it does not even get done.

I believe that some native library that you are using, from the android 7 should not work anymore.
excuse my english

**Comment by erezrokah** [comment] 2018-10-18 10:59
Hey @RaulCorreia I'll try to setup an test environment and look into it during the following week

**Comment by erezrokah** [comment] 2018-10-18 14:57
Hey @RaulCorreia I just updated our example to a new version of react native and tested it on both a Nexus 5X emulator with Android 7.1 and a Nexus 4 Physical device with Lineage OS 15.1 (Android 8.1.0).
Everything seems to work properly (getting settings and listening to events).
Can you please make sure you can make the example here work:
https://github.com/rmrs/react-native-settings/tree/master/example

If that works for you, we can compare the differences between your code and the example code to find the problem.

**Comment by RaulCorreia** [comment] 2018-10-18 16:18
i use your exemple but an interesting thing that I noticed, when I click on change, and go to the settings and change it, the library detects, but if I change by the action bar does not change.
I tested the emulator and the cell phone with api 24.
but when I do the same on a cell phone with api 23, the library works perfectly

an emulator image with the location off
http://prntscr.com/l7m00w

PS: I tested the airplane mode it happens the same

**Comment by erezrokah** [comment] 2018-10-18 18:33
@RaulCorreia thank you again for pointing this problem to us.
Do you mind trying with this branch:
https://github.com/rmrs/react-native-settings/tree/fix_example_event_listeners/example

It looks like one needs to register the receivers explicitly now.
It it works for you I'll update the readme as well as the example.

Thanks

**Comment by farwayer** [comment] 2018-10-18 20:19
@erezrokah just tested on emulator (genymotion) and real device (all api 26):
- old version: works on device, do not work on emulator
- new version: works on device and emulator; if receiver presented in manifest than it fires event several times on device

My suggestions:
- move registration to module code (`RNSettingsModule` constructor) from user `MainApplication`
- note in readme and/or changelog that user should remove receivers from manifest after lib update

**Comment by farwayer** [comment] 2018-10-18 21:11
Or even it may be better to add new method for dynamic registration:
```js
const listener = RNSettings.onChange(RNSettings.LOCATION_SETTING, e => ...);
...
listener.remove();
```
And inside `onChange` in java register receiver if it was not registered before. And remove receiver if no listeners left.

**Comment by RaulCorreia** [comment] 2018-10-18 22:18
@erezrokah using this last example in api 27 and 24 in the emulator worked everything correctly, I'll test tomorrow on the cell phones, thanks for the quick concert

**Comment by erezrokah** [comment] 2018-10-19 08:50
@farwayer and @RaulCorreia thank you for verifying.

@farwayer As listening to events should be optional I'm not sure we should put it in the constructor.
I'll update the readme and add the new method to the changelog (as you suggested) for now.

I'm still not sure about adding a new method as one needs to register the event listeners using react native api anyway, so it might be confusing.

Since changing the readme+changelog is the easiest and fastest (no code changes required in the library) let's see if it is enough at the moment.

**Comment by erezrokah** [comment] 2018-10-19 09:20
Fixed by https://github.com/rmrs/react-native-settings/pull/24
Please re-open if you have any more issues

**Closed by erezrokah** 2018-10-19 09:20 UTC

**Comment by erezrokah** [comment] 2018-10-21 07:59
Hey @farwayer, sorry for the late reply, I wanted to read more about `NativeEventEmitter`.
React native's documentation is a bit confusing as the Android docs use `DeviceEventEmitter` directly:
https://facebook.github.io/react-native/docs/native-modules-android

and the iOS docs wrap it with `NativeEventEmitter`.

I agree it make sense to extend `NativeEventEmitter` as you suggested.

Would you like to submit a pr for it?
